export const ARTICLE = {
  SLUG_CHANGED: 'ARTICLE_SLUG_CHANGED:',
  LOADING: 'ARTICLE_LOADING',
  LOADED: 'ARTICLE_LOADED',
  HAS_ERROR: 'ARTICLE_HAS_ERROR',
};

export const ARTICLE_LIST = {
  LOADING: 'ARTICLE_LIST_LOADING',
  LOADED: 'ARTICLE_LIST_LOADED',
  HAS_ERROR: 'ARTICLE_LIST_HAS_ERROR',
  PAGE_CHANGED: 'ARTICLE_LIST_PAGE_CHANGED',
};
