const ARTICLE = {
  SLUG_CHANGED: 'ARTICLE_SLUG_CHANGED:',
  LOADING: 'ARTICLE_LOADING',
  LOADED: 'ARTICLE_LOADED',
  HAS_ERROR: 'ARTICLE_HAS_ERROR',
};

const ARTICLE_LIST = {
  LOADING: 'ARTICLE_LIST_LOADING',
  LOADED: 'ARTICLE_LIST_LOADED',
  HAS_ERROR: 'ARTICLE_LIST_HAS_ERROR',
  PAGE_CHANGED: 'ARTICLE_LIST_PAGE_CHANGED',
};

const AUTH = {
  ADD_USER: 'ADD_USER',
  LOADING: 'AUTHENTICATION_LOADING',
  LOGGED_IN: 'LOGGED_IN',
};

const actionTypes = {
  ARTICLE,
  ARTICLE_LIST,
  AUTH,
};

export default actionTypes;
